---

global:
  geonodeSiteName: dominode.dm
  geoserverURL: https://dominode.dm/geoserver/
  adminUser: admin
  adminPassword:
    value: duI50BQH9VmH
  databaseHost: dodo.nunez.co
  databaseUsername: dominode
  databaseName: dominode_app
  databasePassword:
    value: 5Bgb7936mam65v
  geodatabaseHost: dodo.nunez.co
  geodatabaseUsername: dominode
  geodatabaseName: dominode
  geodatabasePassword:
    value: 5Bgb7936mam65v
  geoserverAdminPassword:
    value: f2h0Z0Jpny7a

geoserver:
  enabled: true

postgis:
  enabled: false
