# -- (object/container-image) Image map
# @notationType -- yaml
image:
  # -- Image registry
  registry: docker.io
  # -- Image repository
  repository: lucernae/django-sample
  # -- Image tag
  tag: "3.1"
  # -- (k8s/containers/image/imagePullPolicy) Image pullPolicy
  pullPolicy: IfNotPresent


# This key name is used for service interconnection between subcharts and parent charts.
global:
  nameOverride: django
  # -- (tpl/string) Name of existing config
  # @notationType -- tpl
  existingConfig: |
  # -- (tpl/string) Name of existing secret
  # @notationType -- tpl
  existingSecret: |
  # -- (string) Name of shared secret store that will be generated
  sharedSecretName: django-shared-secret
  # -- (string) Name of shared config store that will be generated
  sharedConfigName: django-shared-config
  # generic values
  # -- (string) The site name. It will be used to construct url such as http://django/
  siteName: django
  # -- (tpl/list) The django entrypoint command to execute
  # @notationType -- tpl
  djangoCommand: |
    ["/opt/django/scripts/docker-entrypoint.sh"]
  # -- (tpl/list) The django command args to be passed to entrypoint command
  # @notationType -- tpl
  djangoArgs: |
    ["uwsgi","--chdir=${REPO_ROOT}","--module=${MAIN_APP_NAME}.wsgi","--socket=:8000","--http=0.0.0.0:8080","--processes=5","--buffer-size=8192"]
  # -- (string) Default super user admin username
  adminUser: admin
  # -- (object/common.secret) Secret structure for Admin Password
  # @notationType -- yaml
  adminPassword:
    # -- (string) Specify this password value. If not, it will be autogenerated everytime chart upgraded
    value:
    valueFrom:
      secretKeyRef:
        name:
        key: admin-password
  # -- (string/email) Default admin email sender
  # @notationType -- string/email
  adminEmail: admin@localhost
  # -- (object/common.secret) Secret structure for Django Secret Key
  # @notationType -- yaml
  djangoSecretKey:
    # -- (string) Specify this Django Secret string value. If not, it will be autogenerated everytime chart upgraded
    value:
    valueFrom:
      secretKeyRef:
        name:
        key: django-secret
  # -- (string) Database username backend to connect to. If you use external backend, provide the value
  databaseUsername: django_db_user
  # -- (object/common.secret) Secret structure for Database Password
  # @notationType -- yaml
  databasePassword:
    # -- (string) Specify this password value. If not, it will be autogenerated everytime chart upgraded. If you use external backend, you must provide the value
    value:
    valueFrom:
      secretKeyRef:
        name:
        key: database-password
  # -- (string) Django database name
  databaseName: django
  # -- (string) Django database host location. By default this chart can generate standard postgres chart. So you can leave it as default. If you use external backend,  you must provide the value
  databaseHost:
  # -- (int) Django database port. By default this chart can generate standard postgres chart. So you can leave it as default. If you use external backend,  you must provide the value
  databasePort: 5432
  # -- (string/bool) Python boolean literal, this will correspond to `DEBUG` environment variable inside the Django container. Useful as a debug switch.
  debug: "False"
  # -- (string) The main app name to execute. Affects which settings, wsgi, and rootURL to use.
  mainAppName: django
  # -- (string) Django settings module to be used
  djangoSettingsModule: django.settings
  # -- (string) Django root URL conf to be used
  rootURLConf: django.urls
  # -- (path) Location to the static directory
  staticRoot: /opt/django/static
  # -- (path) Location to the media directory
  mediaRoot: /opt/django/media
  # -- (string) Storage class name used to provision PV
  storageClassName:

  # -- (string) Use this if you want to specify the full
  # Database URL connection
  databaseURL:
    value:
    valueFrom:
      secretKeyRef:
        name:
        key: database-url

# -- (tpl/array) Define this for extra Django environment variables
# @notationType -- tpl
extraPodEnv: |
  - name: DJANGO_SETTINGS_MODULE
    value: "django.settings"
  - name: DEBUG
    value: {{ .Values.global.debug | quote }}
  - name: ROOT_URLCONF
    value: {{ .Values.global.rootURLConf | quote }}
  - name: MAIN_APP_NAME
    value: {{ .Values.global.mainAppName | quote }}

# -- (tpl/object) This will be evaluated as pod spec
# @notationType -- tpl
extraPodSpec: |
#  nodeSelector:
#    a.label: value

# -- (tpl/map) Define this for extra secrets to be included in django-shared-secret secret
# @notationType -- tpl
extraSecret: |
#  key_1: value_1

# -- (tpl/map) Define this for extra config map to be included in django-shared-config
# @notationType -- tpl
extraConfigMap: |
# file_1: conf content

# -- (tpl/list) Define this for extra volume mounts in the pod
# @notationType -- tpl
extraVolumeMounts: |
# You may potentially mount a config map/secret
#  - name: custom-config
#    mountPath: /docker-entrypoint.sh
#    subPath: docker-entrypoint.sh
#    readOnly: true

# -- (tpl/list) Define this for extra volume (in pair with extraVolumeMounts)
# @notationType -- tpl
extraVolume: |
# You may potentially mount a config map/secret
#  - name: custom-config
#    configMap:
#      name: geonode-config

service:
  # -- (string) Define k8s service for Django.
  type: ClusterIP
  # -- (string) Specify `None` for headless service. Otherwise, leave them be.
  clusterIP: ""
  # -- (tpl/array) Specify for LoadBalancer service type
  # @notationType -- tpl
  externalIPs: |
  # -- (int) Specify service port
  port: 80

  # -- (int) Specify node port, for NodePort service type
  nodePort:

  # -- (dict) Extra service annotations
  annotations: {}

ingress:
  # -- (bool) Set to true to generate Ingress resource
  enabled: false
  # -- (tpl/string) Set custom host name. (DNS name convention)
  # @notationType -- tpl
  host: |
  # -- (dict) Custom Ingress annotations
  annotations: {}
  # -- (dict) Custom Ingress labels
  labels: {}
  tls:
    # -- (bool) Set to true to enable HTTPS
    enabled: false
    # -- (string) You must provide a secret name where the TLS cert is stored
    secretName: django-tls

# -- (tpl/object) Probe can be overridden
# @notationType -- tpl
probe: |

postgis:
  # -- (bool) Enable postgis as database backend by default. Set to false if using different external backend.
  enabled: true
  postgresqlUsername: superuser
  # -- (tpl/string) Existing secret to be used
  # @notationType -- tpl
  existingSecret: |

  # -- (tpl/object) Extra config map for postgis to be included
  # Can be used to pregenerate Django database for first setup
  # @notationType -- tpl
  extraConfigMap: |
    django-db.sh: |
      #!/usr/bin/env bash
      DATABASE="{{ .Values.global.databaseName }}"
      # password comes from environment variables, so it can be retrieved from secret
      DATABASE_USER="{{ .Values.global.databaseUsername }}"
      # create database
      su postgres -c "createdb ${DATABASE}"
      # create role
      cat << EOF | su postgres -c "psql"
      CREATE ROLE ${DATABASE_USER};
      EOF
      # modify permissions
      cat << EOF | su postgres -c "psql -d ${DATABASE}"
      -- Create role
      ALTER ROLE ${DATABASE_USER} LOGIN PASSWORD '${DATABASE_PASSWORD}';
      ALTER DATABASE ${DATABASE} OWNER TO ${DATABASE_USER};
      EOF

  # -- (tpl/array) Extra pod env for postgis
  # We expose Django database password in case we need to pregenerate it
  # @notationType -- tpl
  extraPodEnv: |
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ include "common.sharedSecretName" . | quote }}
          key: {{ .Values.global.databasePassword.valueFrom.secretKeyRef.key }}

  # -- (tpl/array) Extra volume declaration for postgis
  # We use extra volume to mount postgis configmap to pregenerate database
  # @notationType -- tpl
  extraVolume: |
    - name: config-volume
      configMap:
        name: {{ template "postgis.fullname" . }}
        defaultMode: 0755

  # -- (tpl/array) Extra volume mounts for postgis
  # We use extra volume mounts postgis configmap to pregenerate database
  # @notationType -- tpl
  extraVolumeMounts: |
    - mountPath: /docker-entrypoint-initdb.d/django-db.sh
      subPath: django-db.sh
      name: config-volume


persistence:
  staticDir:
    # -- (bool) Allow persistence
    enabled: false
    # -- (string) Set to an existing claim if you have it
    existingClaim: false
    # -- (path) This has to be the same with [global.staticRoot](#global--staticroot)
    mountPath: /opt/django/static
    subPath: "static"
    size: 8Gi
    accessModes:
      - ReadWriteOnce
    annotations: {}
  mediaDir:
    # -- (bool) Allow persistence
    enabled: true
    # -- (string) Set to an existing claim if you have it
    existingClaim: false
    # -- (path) This has to be the same with [global.mediaRoot](#global--mediaroot)
    mountPath: /opt/django/media
    subPath: "media"
    size: 8Gi
    accessModes:
      - ReadWriteOnce
    annotations: {}

test:
  django:
    # -- (tpl/array) List of containers override for testing
    # @notationType -- (tpl)
    containers: |
