---
geoserverDataDir: /opt/mygeoserver/data_dir
geowebcacheCacheDir: /opt/mygeoserver/gwc

geoserverUser: superadmin
geoserverPassword: superpasswordlol

persistence:
  geoserverDataDir:
    mountPath: /opt/mygeoserver/data_dir
  geowebcacheCacheDir:
    mountPath: /opt/mygeoserver/gwc

ingress:
  enabled: true
  host: geoserver.test
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
  tls:
    enabled: true
    secretName: geoserver-tls
