apiVersion: v2
name: django
version: 0.2.2
appVersion: "3.1"
description: Generic chart for basic Django-based web app
keywords:
  - Django
  - Web
home: https://www.djangoproject.com/
sources:
  - https://github.com/django/django
maintainers:
  - name: lucernae
    email: lana.pcfre@gmail.com
icon: https://raw.githubusercontent.com/kartoza/charts/master/assets/logo/django.png
engine: gotpl
dependencies:
  - name: postgis
    version: 0.2.2
    repository: "file://../../postgis/v0.2.2"
    condition: postgis.enabled
    tags:
      - database-backend
      - postgis
  - name: common
    version: 1.0.1
    repository: "file://../../common/v1.0.1"
