{{- define "common.secret.tpl" -}}
apiVersion: v1
kind: Secret
{{ include "common.metadata.tpl" . }}
type: Opaque
data: {}
{{- end -}}
{{- define "common.secret" -}}
{{ include "common.util.merge" (append . "common.secret.tpl") }}
{{- end -}}
