apiVersion: v2
name: qgis-server
version: 0.2.1
appVersion: 3.14
description: Chart for QGIS-Server
keywords:
  - QGIS
  - QGIS Server
  - GIS
home: https://qgis.org
sources:
  - https://github.com/qgis/QGIS
maintainers:
  - name: lucernae
    email: lana.pcfre@gmail.com
engine: gotpl
icon: https://raw.githubusercontent.com/kartoza/charts/master/assets/logo/qgis-server.png
