apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "qgisserver.fullname" . }}
  labels:
    app: {{ template "qgisserver.fullname" . }}
    chart: {{ template "qgisserver.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- with .Values.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "qgisserver.fullname" . }}
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      name: {{ template "qgisserver.fullname" . }}
      labels:
        app: {{ template "qgisserver.fullname" . }}
        chart: {{ template "qgisserver.chart" . }}
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
        {{- with .Values.podLabels }}
        {{- tpl . $ | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- (tpl . $) | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        - name: check-qgis-project-exists
          image: busybox:1.28
          command: ['sh', '-c', 'if ! ls -A {{ .Values.qgisServerProjectFile | quote }}; then echo "Copying default empty project: empty.qgz"; cp /data/empty.qgz {{ .Values.qgisServerProjectFile | quote }}; fi' ]
          volumeMounts:
            - name: config-volume
              mountPath: /data/empty.qgz
              subPath: empty.qgz
            {{- if .Values.persistence.qgisServerProjectDir.enabled }}
            - name: qgisserver-project-dir
              mountPath: {{ .Values.persistence.qgisServerProjectDir.mountPath }}
              subPath: {{ .Values.persistence.qgisServerProjectDir.subPath }}
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- (tpl . $) | nindent 12 }}
            {{- end }}

      containers:
        - name: {{ template "qgisserver.fullname" . }}
          image: {{ template "qgisserver.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.qgisServerProjectDir }}
            - name: QGIS_PROJECT_DIR
              value: {{ .Values.qgisServerProjectDir | quote }}
            {{- end }}
            {{- if .Values.qgisServerProjectFile }}
            - name: QGIS_PROJECT_FILE
              value: {{ .Values.qgisServerProjectFile | quote }}
            {{- end }}
            {{- with .Values.extraPodEnv }}
            {{- tpl . $ | nindent 12 }}
            {{- end }}
          ports:
            - name: http-qgisserver
              containerPort: 80
          {{- if .Values.probe }}
            {{- with .Values.probe }}
            {{- tpl . $ | nindent 10 }}
            {{- end }}
          {{- else }}
          startupProbe:
            httpGet:
              path: {{ printf "%s?SERVICE=WMS&REQUEST=GetCapabilities" .Values.qgisServerBaseOWSURL | quote }}
              port: http-qgisserver
            failureThreshold: 60
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: {{ printf "%s?SERVICE=WMS&REQUEST=GetCapabilities" .Values.qgisServerBaseOWSURL | quote }}
              port: http-qgisserver
              scheme: HTTP
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: {{ printf "%s?SERVICE=WMS&REQUEST=GetCapabilities" .Values.qgisServerBaseOWSURL | quote }}
              port: http-qgisserver
              scheme: HTTP
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
          {{- end }}
          volumeMounts:
            {{- if .Values.persistence.qgisServerProjectDir.enabled }}
            - name: qgisserver-project-dir
              mountPath: {{ .Values.persistence.qgisServerProjectDir.mountPath }}
              subPath: {{ .Values.persistence.qgisServerProjectDir.subPath }}
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- (tpl . $) | nindent 12 }}
            {{- end }}
        {{- with .Values.extraContainers }}
        {{- tpl . $ | nindent 8 }}
        {{- end }}
      {{- with .Values.extraPodSpec }}
      {{- tpl . $ | nindent 6 }}
      {{- end }}
      volumes:
        {{- with .Values.extraVolume }}
        {{- (tpl . $) | nindent 8 }}
        {{- end }}
        - name: config-volume
          configMap:
            name: {{ template "qgisserver.fullname" . }}
            defaultMode: 0644
{{- if and .Values.persistence.qgisServerProjectDir.enabled .Values.persistence.qgisServerProjectDir.existingClaim }}
        - name: qgisserver-project-dir
          persistentVolumeClaim:
{{- with .Values.persistence.qgisServerProjectDir.existingClaim }}
            claimName: {{ tpl . $ }}
{{- end }}
{{- else if .Values.persistence.qgisServerProjectDir.enabled }}
        - name: qgisserver-project-dir
          persistentVolumeClaim:
            claimName: {{ template "qgisserver.fullname" . }}-qgisserver-project-dir
{{- else if not .Values.persistence.qgisServerProjectDir.enabled }}
        - name: qgisserver-project-dir
          emptyDir: {}
{{- end }}
