apiVersion: v1
kind: Service
metadata:
  name: {{ template "qgisserver.fullname" . }}
  labels:
    app: {{ template "qgisserver.fullname" . }}
    chart: {{ template "qgisserver.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    kubernetes.io/cluster-service: "true"
    {{- with .Values.service.labels }}
    {{- tpl . $ | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- tpl . $ | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  {{- if .Values.service.externalIPs }}
  externalIPs: {{ .Values.service.externalIPs }}
  {{- end }}
  ports:
    - name: http-qgisserver
      port: 80
      protocol: TCP
      targetPort: http-qgisserver
  selector:
    app: {{ template "qgisserver.fullname" . }}
    release: {{ .Release.Name | quote }}
