{{- define "common.configmap.tpl" -}}
apiVersion: v1
kind: ConfigMap
{{ include "common.metadata.tpl" . }}
data: {}
{{- end -}}
{{- define "common.configmap" -}}
{{ include "common.util.merge" (append . "common.configmap.tpl") }}
{{- end -}}
